version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 10
    reviewers:
      - "AyushChothe"
    assignees:
      - "AyushChothe"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
      include: "scope"
